// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC_backend.Services;

#nullable disable

namespace PC_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PC_backend.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnswerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<int?>("IsCorrect")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    b.HasKey("AnswerId")
                        .HasName("PK__Answer__D482502411C318F2");

                    b.HasIndex(new[] { "QuestionId" }, "idx_answer_question");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LandlineNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NativeLanguage")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CandidateId")
                        .HasName("PK__Candidat__DF539BFCC8236A3C");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Email" }, "idx_candidate_email");

                    b.HasIndex(new[] { "FirstName", "LastName" }, "idx_candidate_name");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("PC_backend.Models.CandidateAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AddressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<string>("CountryOfResidence")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StateTerritoryProvince")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TownCity")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AddressId")
                        .HasName("PK__Candidat__091C2A1BF29327D8");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateAddress", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.CandidatePhotoId", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhotoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<DateTime?>("PhotoIdissueDate")
                        .HasColumnType("date")
                        .HasColumnName("PhotoIDIssueDate");

                    b.Property<string>("PhotoIdnumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PhotoIDNumber");

                    b.Property<string>("PhotoIdtype")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PhotoIDType");

                    b.HasKey("PhotoId")
                        .HasName("PK__Candidat__21B7B5824D841CCC");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidatePhotoID", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<string>("AssessmentResultLabel")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssessmentTestCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<int?>("CandidateScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExaminationDate")
                        .HasColumnType("date");

                    b.Property<int?>("MaximumScore")
                        .HasColumnType("int");

                    b.Property<double?>("PercentageScore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ScoreReportDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CertificateId")
                        .HasName("PK__Certific__BBF8A7E194BC76C0");

                    b.HasIndex(new[] { "CandidateId" }, "idx_certificate_candidate");

                    b.HasIndex(new[] { "Title" }, "idx_certificate_title");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.CertificateTopicMark", b =>
                {
                    b.Property<int>("CertificateTopicMarksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CertificateTopicMarksID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateTopicMarksId"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    b.Property<int?>("NumberOfAwardedMarks")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfPossibleMarks")
                        .HasColumnType("int");

                    b.Property<string>("TopicDesc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CertificateTopicMarksId")
                        .HasName("PK__Certific__2C7F0986A9C2E005");

                    b.HasIndex("CertificateId");

                    b.ToTable("CertificateTopicMarks");
                });

            modelBuilder.Entity("PC_backend.Models.EshopProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ProductId")
                        .HasName("PK__EshopPro__B40CC6ED8F2F8F97");

                    b.ToTable("EshopProduct", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("date");

                    b.Property<int?>("PassingMark")
                        .HasColumnType("int");

                    b.Property<string>("TestCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("ExamId")
                        .HasName("PK__Exam__297521A754380D3D");

                    b.HasIndex(new[] { "CandidateId" }, "idx_exam_candidate");

                    b.HasIndex(new[] { "DateTaken" }, "idx_exam_date");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.ExamResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ResultID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<int?>("Passed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnType("date");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__ExamResu__97690228236B9C66");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamResult", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.ExamVoucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VoucherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CandidateID");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("date");

                    b.Property<int?>("IsUsed")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("date");

                    b.HasKey("VoucherId")
                        .HasName("PK__ExamVouc__3AEE79C17C99702A");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExamVoucher", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8C7ACDC3F7");

                    b.HasIndex(new[] { "ExamId" }, "idx_question_exam");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleDescription")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__UserRole__8AFACE3A66966242");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Usertbl", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Usertbl__1788CCACB137FABB");

                    b.HasIndex("RoleId");

                    b.ToTable("Usertbl", (string)null);
                });

            modelBuilder.Entity("PC_backend.Models.Answer", b =>
                {
                    b.HasOne("PC_backend.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Answer__Question__57DD0BE4");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PC_backend.Models.Candidate", b =>
                {
                    b.HasOne("PC_backend.Models.Usertbl", "User")
                        .WithMany("Candidates")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Candidate__UserI__43D61337");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PC_backend.Models.CandidateAddress", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("CandidateAddresses")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__Candidate__Candi__498EEC8D");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PC_backend.Models.CandidatePhotoId", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("CandidatePhotoIds")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__Candidate__Candi__46B27FE2");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PC_backend.Models.Certificate", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("Certificates")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__Certifica__Candi__4C6B5938");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PC_backend.Models.CertificateTopicMark", b =>
                {
                    b.HasOne("PC_backend.Models.Certificate", "Certificate")
                        .WithMany("CertificateTopicMarks")
                        .HasForeignKey("CertificateId")
                        .HasConstraintName("FK__Certifica__Certi__4F47C5E3");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("PC_backend.Models.Exam", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("Exams")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__Exam__CandidateI__5224328E");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("PC_backend.Models.ExamResult", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("ExamResults")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__ExamResul__Candi__5BAD9CC8");

                    b.HasOne("PC_backend.Models.Certificate", "Certificate")
                        .WithMany("ExamResults")
                        .HasForeignKey("CertificateId")
                        .HasConstraintName("FK__ExamResul__Certi__5CA1C101");

                    b.HasOne("PC_backend.Models.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK__ExamResul__ExamI__5AB9788F");

                    b.Navigation("Candidate");

                    b.Navigation("Certificate");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("PC_backend.Models.ExamVoucher", b =>
                {
                    b.HasOne("PC_backend.Models.Candidate", "Candidate")
                        .WithMany("ExamVouchers")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__ExamVouch__Candi__625A9A57");

                    b.HasOne("PC_backend.Models.EshopProduct", "Product")
                        .WithMany("ExamVouchers")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ExamVouch__Produ__6166761E");

                    b.Navigation("Candidate");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PC_backend.Models.Question", b =>
                {
                    b.HasOne("PC_backend.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK__Question__ExamID__55009F39");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("PC_backend.Models.Usertbl", b =>
                {
                    b.HasOne("PC_backend.Models.UserRole", "Role")
                        .WithMany("Usertbls")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Usertbl__RoleID__40F9A68C");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PC_backend.Models.Candidate", b =>
                {
                    b.Navigation("CandidateAddresses");

                    b.Navigation("CandidatePhotoIds");

                    b.Navigation("Certificates");

                    b.Navigation("ExamResults");

                    b.Navigation("ExamVouchers");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("PC_backend.Models.Certificate", b =>
                {
                    b.Navigation("CertificateTopicMarks");

                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("PC_backend.Models.EshopProduct", b =>
                {
                    b.Navigation("ExamVouchers");
                });

            modelBuilder.Entity("PC_backend.Models.Exam", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PC_backend.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PC_backend.Models.UserRole", b =>
                {
                    b.Navigation("Usertbls");
                });

            modelBuilder.Entity("PC_backend.Models.Usertbl", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
